-- Migration 006: PI-owned paper catalog (additive / shadow).
-- Does NOT modify Research Radar tables.
-- Does NOT migrate or drop legacy FKs to research_radar.content_items.
--
-- Apply manually:
--   psql "$DATABASE_URL" -f sql/migrations/006_pi_papers_catalog.sql

BEGIN;

-- Canonical PI paper identity. paper_id may equal legacy content_item_id
-- when backfilled with OVERRIDING SYSTEM VALUE (validated precheck).
CREATE TABLE IF NOT EXISTS paper_intelligence.papers (
    paper_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_content_item_id BIGINT UNIQUE,
    arxiv_id              TEXT,
    arxiv_version         INTEGER,
    doi                   TEXT,
    source                TEXT NOT NULL,
    source_external_id    TEXT,
    source_type           TEXT,
    canonical_url         TEXT,
    title                 TEXT NOT NULL,
    abstract              TEXT,
    summary               TEXT,
    categories            JSONB NOT NULL DEFAULT '[]'::jsonb,
    authors_raw           JSONB,
    authors_structured    JSONB,
    affiliation_text      JSONB,
    extracted_emails      JSONB,
    published_at          TIMESTAMPTZ,
    source_updated_at     TIMESTAMPTZ,
    ingested_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT papers_source_external_uniq UNIQUE (source, source_external_id)
);

-- Normalized identity uniqueness (NULLs allowed / not unique among NULLs).
CREATE UNIQUE INDEX IF NOT EXISTS ux_papers_arxiv_id
    ON paper_intelligence.papers (arxiv_id)
    WHERE arxiv_id IS NOT NULL AND arxiv_id <> '';

CREATE UNIQUE INDEX IF NOT EXISTS ux_papers_doi
    ON paper_intelligence.papers (doi)
    WHERE doi IS NOT NULL AND doi <> '';

CREATE INDEX IF NOT EXISTS ix_papers_published_at
    ON paper_intelligence.papers (published_at DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS ix_papers_ingested_at
    ON paper_intelligence.papers (ingested_at DESC);

-- Crosswalk for external systems (Radar, arXiv, DOI, HF).
CREATE TABLE IF NOT EXISTS paper_intelligence.paper_identity_map (
    map_id       BIGSERIAL PRIMARY KEY,
    paper_id     BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE CASCADE,
    system       TEXT NOT NULL,
    external_id  TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT paper_identity_map_system_external_uniq UNIQUE (system, external_id)
);

CREATE INDEX IF NOT EXISTS ix_paper_identity_map_paper
    ON paper_intelligence.paper_identity_map (paper_id);

-- Append-only PI relevance decisions (funnel truth — not papers.status).
CREATE TABLE IF NOT EXISTS paper_intelligence.paper_relevance_results (
    relevance_id     BIGSERIAL PRIMARY KEY,
    paper_id         BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE CASCADE,
    decision         TEXT NOT NULL
        CHECK (decision IN ('keep', 'reject')),
    score            DOUBLE PRECISION,
    reason           TEXT,
    method           TEXT NOT NULL DEFAULT 'migrated',
    stage_version    TEXT,
    prompt_version   TEXT,
    policy_version   TEXT,
    model            TEXT,
    run_id           UUID
        REFERENCES paper_intelligence.pipeline_runs(run_id) ON DELETE SET NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_paper_relevance_results_paper_created
    ON paper_intelligence.paper_relevance_results (paper_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_paper_relevance_results_decision
    ON paper_intelligence.paper_relevance_results (decision, created_at DESC);

-- PI-owned ingest checkpoints (Radar backfill_checkpoints remain untouched).
CREATE TABLE IF NOT EXISTS paper_intelligence.ingest_checkpoints (
    checkpoint_id    BIGSERIAL PRIMARY KEY,
    source           TEXT NOT NULL,
    set_spec         TEXT,
    window_from      TIMESTAMPTZ,
    window_until     TIMESTAMPTZ,
    status           TEXT NOT NULL DEFAULT 'running',
    records_seen     INTEGER NOT NULL DEFAULT 0,
    records_kept     INTEGER NOT NULL DEFAULT 0,
    records_new      INTEGER NOT NULL DEFAULT 0,
    records_dupe     INTEGER NOT NULL DEFAULT 0,
    error            TEXT,
    started_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at         TIMESTAMPTZ,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_ingest_checkpoints_source_started
    ON paper_intelligence.ingest_checkpoints (source, started_at DESC);

-- NOTE: paper_intelligence.s3_archives intentionally NOT created.
-- PI reject archival still writes research_radar.s3_archives as compatibility.

COMMIT;
