-- Migration 010: Affiliation HTML↔ OpenAlex verification work claims.
-- Additive. Supports multi-worker claim with FOR UPDATE SKIP LOCKED.
--
-- Apply:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f sql/migrations/010_affiliation_verifications.sql

BEGIN;

CREATE TABLE IF NOT EXISTS paper_intelligence.affiliation_verifications (
    verification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id          BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE NO ACTION,
    verification_version TEXT NOT NULL,
    status            TEXT NOT NULL DEFAULT 'pending'
        CHECK (status = ANY (ARRAY[
            'pending'::text,
            'running'::text,
            'complete'::text,
            'failed'::text
        ])),
    outcome           TEXT
        CHECK (
            outcome IS NULL OR outcome = ANY (ARRAY[
                'verified_agreement'::text,
                'partial_agreement'::text,
                'verified_html_primary'::text,
                'verified_openalex_primary'::text,
                'conflict'::text,
                'unresolved'::text
            ])
        ),
    claimed_at        TIMESTAMPTZ,
    started_at        TIMESTAMPTZ,
    completed_at      TIMESTAMPTZ,
    worker_id         TEXT,
    attempt_count     INTEGER NOT NULL DEFAULT 0,
    error             TEXT,
    result_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    modified_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT affiliation_verifications_paper_version_uniq
        UNIQUE (verification_version, paper_id)
);

CREATE INDEX IF NOT EXISTS ix_aff_verify_claim
    ON paper_intelligence.affiliation_verifications (verification_version, status, claimed_at);

CREATE INDEX IF NOT EXISTS ix_aff_verify_outcome
    ON paper_intelligence.affiliation_verifications (verification_version, outcome);

COMMIT;
