-- Migration 012: LLM affiliation judge outcomes (disagreement path only).
-- Additive. Does not alter existing HTML/OpenAlex evidence rows.

BEGIN;

CREATE TABLE IF NOT EXISTS paper_intelligence.affiliation_judgments (
    judgment_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id          BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE NO ACTION,
    judge_version     TEXT NOT NULL,
    compare_status    TEXT NOT NULL
        CHECK (compare_status = ANY (ARRAY[
            'exact_match'::text,
            'disagreement'::text,
            'html_only'::text,
            'openalex_only'::text,
            'neither'::text,
            'oa_unavailable'::text
        ])),
    decision          TEXT
        CHECK (
            decision IS NULL OR decision = ANY (ARRAY[
                'HTML'::text,
                'OPENALEX'::text,
                'BOTH'::text,
                'UNCERTAIN'::text,
                'AUTO_AGREE'::text,
                'AUTO_HTML'::text,
                'AUTO_SKIP'::text
            ])
        ),
    judge_called      BOOLEAN NOT NULL DEFAULT FALSE,
    model             TEXT,
    prompt_version    TEXT,
    accepted_organisation_ids BIGINT[] NOT NULL DEFAULT '{}',
    result_json       JSONB NOT NULL DEFAULT '{}'::jsonb,
    reason            TEXT,
    estimated_cost_usd NUMERIC(10,6),
    input_tokens      INTEGER,
    output_tokens     INTEGER,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT affiliation_judgments_paper_version_uniq
        UNIQUE (judge_version, paper_id)
);

CREATE INDEX IF NOT EXISTS ix_aff_judge_status
    ON paper_intelligence.affiliation_judgments (judge_version, compare_status);

COMMIT;
