-- Migration 014: quality_attempts + allow quality_status='pending'.
-- Additive. Does not delete or rewrite existing result rows.
--
-- quality_attempts records per-paper LLM quality try outcomes so adjudication
-- can distinguish failed calls from never-selected / still-pending papers.
-- Failures are NOT written to paper_classification_results (keeps skip/retry
-- based on successful rows only).

BEGIN;

CREATE TABLE IF NOT EXISTS paper_intelligence.quality_attempts (
    attempt_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_item_id   BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE NO ACTION,
    run_id            TEXT,
    stage_run_id      TEXT,
    stage_version     TEXT NOT NULL,
    prompt_version    TEXT NOT NULL,
    policy_version    TEXT NOT NULL,
    model             TEXT NOT NULL,
    status            TEXT NOT NULL
        CHECK (status = ANY (ARRAY[
            'succeeded'::text,
            'failed'::text
        ])),
    error_summary     TEXT,
    attempted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_quality_attempts_paper_versions
    ON paper_intelligence.quality_attempts (
        content_item_id, stage_version, prompt_version, policy_version, model, attempted_at DESC
    );

CREATE INDEX IF NOT EXISTS ix_quality_attempts_status
    ON paper_intelligence.quality_attempts (status, attempted_at DESC);

-- Allow 'pending' on current-state quality_status (migration 005 vocabulary).
ALTER TABLE paper_intelligence.paper_intelligence_current
    DROP CONSTRAINT IF EXISTS paper_intelligence_current_quality_status_check;

ALTER TABLE paper_intelligence.paper_intelligence_current
    ADD CONSTRAINT paper_intelligence_current_quality_status_check
    CHECK (
        quality_status IS NULL
        OR quality_status = ANY (ARRAY[
            'not_selected'::text,
            'scored'::text,
            'failed'::text,
            'skipped'::text,
            'pending'::text
        ])
    );

COMMIT;
