-- Migration 016: content fingerprints for catalog + classification reuse.
-- Additive. Nullable columns so legacy rows remain reusable (NULL hash).

BEGIN;

ALTER TABLE paper_intelligence.papers
    ADD COLUMN IF NOT EXISTS content_hash TEXT;

ALTER TABLE paper_intelligence.paper_classification_results
    ADD COLUMN IF NOT EXISTS input_content_hash TEXT;

CREATE INDEX IF NOT EXISTS ix_papers_content_hash
    ON paper_intelligence.papers (content_hash)
    WHERE content_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_classification_input_content_hash
    ON paper_intelligence.paper_classification_results (content_item_id, input_content_hash)
    WHERE input_content_hash IS NOT NULL;

-- Append-only log when ingest changes title/abstract fingerprint.
CREATE TABLE IF NOT EXISTS paper_intelligence.paper_content_hash_changes (
    change_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id          BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE NO ACTION,
    previous_hash     TEXT,
    new_hash          TEXT NOT NULL,
    arxiv_version     INTEGER,
    changed_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source            TEXT NOT NULL DEFAULT 'arxiv_oai',
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_paper_content_hash_changes_paper
    ON paper_intelligence.paper_content_hash_changes (paper_id, changed_at DESC);

COMMENT ON COLUMN paper_intelligence.papers.content_hash IS
    'sha256 of NFC + whitespace-collapsed title+abstract';
COMMENT ON COLUMN paper_intelligence.paper_classification_results.input_content_hash IS
    'content_hash of the paper text scored by this result; NULL = legacy reusable';

COMMIT;
