-- Migration 018: screen_attempts — per-paper screen LLM try outcomes.
-- Additive. Mirrors quality_attempts so missing/failed screens appear in funnel.
-- Failures are NOT written to paper_classification_results (keeps skip/retry
-- based on successful rows only).

BEGIN;

CREATE TABLE IF NOT EXISTS paper_intelligence.screen_attempts (
    attempt_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_item_id   BIGINT NOT NULL
        REFERENCES paper_intelligence.papers(paper_id) ON DELETE NO ACTION,
    run_id            TEXT,
    stage_run_id      TEXT,
    stage_version     TEXT NOT NULL,
    prompt_version    TEXT NOT NULL,
    policy_version    TEXT NOT NULL,
    model             TEXT NOT NULL,
    status            TEXT NOT NULL
        CHECK (status = ANY (ARRAY[
            'succeeded'::text,
            'failed'::text
        ])),
    error_summary     TEXT,
    attempted_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata          JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_screen_attempts_paper_versions
    ON paper_intelligence.screen_attempts (
        content_item_id, stage_version, prompt_version, policy_version, model, attempted_at DESC
    );

CREATE INDEX IF NOT EXISTS ix_screen_attempts_status
    ON paper_intelligence.screen_attempts (status, attempted_at DESC);

COMMIT;
